---
title: "Group Project"
output: pdf_document
date: "2025-06-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(ggplot2)
library(reshape2)
library(pheatmap)
library(dplyr)

dataframe <- read.csv(file = "gene-expression-invasive-vs-noninvasive-cancer.csv")
dataframe$CancerType <- ifelse(dataframe$Class == 1, "Non-invasive", "Invasive")

# --- Example subset using my registration number ---  
group_number <- 7

# --- Loading Subset Dataframe ----
df_subsets <- read.csv(file = "teamsubsets.csv", sep=' ')

# --- Filtering my registration number ---
reg_id <- df_subsets[group_number, ]

# --- Extracting variables indexes from subsets data ---
subsets <- unlist(c(df_subsets[reg_id, -1]))

Class <- dataframe$Class # Extract the "Class" column, which represents the labels or targets.

# --- Filtering columns from dataframe gene-expression-invasive-vs-noninvasive-cancer ---
df <- dataframe[, subsets] 


# Count the categories
counts <- table(dataframe$CancerType)
print(counts)
# Plot
barplot(counts,
        main = "Cancer Type Counts",
        col = c("skyblue", "salmon"),
        ylab = "Number of Cases")

```


```{r pressure, echo=FALSE}
# Shuffle entire dataframe
dataframe <- dataframe[sample(nrow(dataframe)), ]

# Separate fraud and non-fraud
fraud_df <- dataframe %>% filter(Class == 1)
non_fraud_df <- dataframe %>% filter(Class == 0) %>% slice(1:492)

# Combine and shuffle again
normal_distributed_df <- bind_rows(fraud_df, non_fraud_df)
set.seed(42)
new_df <- normal_distributed_df[sample(nrow(normal_distributed_df)), ]

counts <- table(new_df$CancerType)
print(counts)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
